2025-07-06 02:10:49,717 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-06 02:10:49,717 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-06 02:10:49,718 INFO sqlalchemy.engine.Engine SELECT 1
2025-07-06 02:10:49,718 - sqlalchemy.engine.Engine - INFO - SELECT 1
2025-07-06 02:10:49,720 INFO sqlalchemy.engine.Engine [cached since 62.08s ago] ()
2025-07-06 02:10:49,720 - sqlalchemy.engine.Engine - INFO - [cached since 62.08s ago] ()
2025-07-06 02:10:49,724 INFO sqlalchemy.engine.Engine INSERT INTO audit_log (id, user_id, user_type, action, resource, resource_id, details, ip_address, user_agent) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
2025-07-06 02:10:49,724 - sqlalchemy.engine.Engine - INFO - INSERT INTO audit_log (id, user_id, user_type, action, resource, resource_id, details, ip_address, user_agent) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
2025-07-06 02:10:49,725 INFO sqlalchemy.engine.Engine [cached since 62.08s ago] (UUID('a441510f-7688-4d00-9fa4-2a3e8120f385'), UUID('2e418704-07da-448d-94a1-7bacf5f91b75'), 'user', 'REGISTER', 'PATIENT', UUID('373788c0-0972-4754-9ac7-fe90eb2fa630'), 'Staff nurse registered patient +98723946234', '127.0.0.1', 
'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0')
2025-07-06 02:10:49,725 - sqlalchemy.engine.Engine - INFO - [cached since 62.08s ago] (UUID('a441510f-7688-4d00-9fa4-2a3e8120f385'), UUID('2e418704-07da-448d-94a1-7bacf5f91b75'), 'user', 'REGISTER', 'PATIENT', UUID('373788c0-0972-4754-9ac7-fe90eb2fa630'), 'Staff nurse registered patient +98723946234', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0')
2025-07-06 02:10:49,730 INFO sqlalchemy.engine.Engine COMMIT
2025-07-06 02:10:49,730 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-07-06 02:10:49,732 - main - INFO - Request: POST http://localhost:8000/api/v1/staff/appointments
2025-07-06 02:10:49,733 - api.dependencies - INFO - Audit log created: register on patient by user:2e418704-07da-448d-94a1-7bacf5f91b75
2025-07-06 02:10:49,736 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-06 02:10:49,736 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-06 02:10:49,738 INFO sqlalchemy.engine.Engine SELECT users.id, users.username, users.password_hash, users.email, users.first_name, users.last_name, users.role, users.is_active, users.created_at, users.updated_at
FROM users
WHERE users.id = %s
2025-07-06 02:10:49,738 - sqlalchemy.engine.Engine - INFO - SELECT users.id, users.username, users.password_hash, users.email, users.first_name, users.last_name, users.role, users.is_active, users.created_at, users.updated_at
FROM users
WHERE users.id = %s
2025-07-06 02:10:49,739 INFO sqlalchemy.engine.Engine [cached since 61.93s ago] (UUID('2e418704-07da-448d-94a1-7bacf5f91b75'),)
2025-07-06 02:10:49,739 - sqlalchemy.engine.Engine - INFO - [cached since 61.93s ago] (UUID('2e418704-07da-448d-94a1-7bacf5f91b75'),)
2025-07-06 02:10:49,752 INFO sqlalchemy.engine.Engine SELECT patients.id, patients.phone_number, patients.password_hash, patients.first_name, patients.last_name, patients.date_of_birth, patients.gender, patients.email, patients.address, patients.emergency_contact, patients.emergency_contact_name, patients.emergency_contact_relationship, patients.is_active, patients.created_at, patients.updated_at
FROM patients
WHERE patients.id = %s
2025-07-06 02:10:49,752 - sqlalchemy.engine.Engine - INFO - SELECT patients.id, patients.phone_number, patients.password_hash, patients.first_name, patients.last_name, patients.date_of_birth, patients.gender, patients.email, patients.address, patients.emergency_contact, patients.emergency_contact_name, patients.emergency_contact_relationship, patients.is_active, patients.created_at, patients.updated_at
FROM patients
WHERE patients.id = %s
2025-07-06 02:10:49,755 INFO sqlalchemy.engine.Engine [generated in 0.00398s] (UUID('373788c0-0972-4754-9ac7-fe90eb2fa630'),)
2025-07-06 02:10:49,755 - sqlalchemy.engine.Engine - INFO - [generated in 0.00398s] (UUID('373788c0-0972-4754-9ac7-fe90eb2fa630'),)
2025-07-06 02:10:49,763 INFO sqlalchemy.engine.Engine SELECT appointments.doctor_id, count(queue.id) AS queue_count 
FROM appointments JOIN queue ON queue.appointment_id = appointments.id
WHERE queue.status IN (%s, %s) AND CURRENT_DATE = date(queue.created_at) GROUP BY appointments.doctor_id ORDER BY queue_count ASC
2025-07-06 02:10:49,763 - sqlalchemy.engine.Engine - INFO - SELECT appointments.doctor_id, count(queue.id) AS queue_count
FROM appointments JOIN queue ON queue.appointment_id = appointments.id
WHERE queue.status IN (%s, %s) AND CURRENT_DATE = date(queue.created_at) GROUP BY appointments.doctor_id ORDER BY queue_count ASC
2025-07-06 02:10:49,763 INFO sqlalchemy.engine.Engine [generated in 0.00159s] ('WAITING', 'CALLED')
2025-07-06 02:10:49,763 - sqlalchemy.engine.Engine - INFO - [generated in 0.00159s] ('WAITING', 'CALLED')
Creating appointment directly
2025-07-06 02:10:49,775 INFO sqlalchemy.engine.Engine INSERT INTO appointments (id, patient_id, doctor_id, created_by, appointment_date, reason, urgency, status) VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING appointments.id
2025-07-06 02:10:49,775 - sqlalchemy.engine.Engine - INFO - INSERT INTO appointments (id, patient_id, doctor_id, created_by, appointment_date, reason, urgency, status) VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING appointments.id
2025-07-06 02:10:49,778 INFO sqlalchemy.engine.Engine [generated in 0.00112s] (UUID('09170749-d492-487c-b99d-e3fa7a35042b'), UUID('373788c0-0972-4754-9ac7-fe90eb2fa630'), None, UUID('2e418704-07da-448d-94a1-7bacf5f91b75'), datetime.datetime(2025, 7, 5, 0, 0), 'Fever', 'NORMAL', 'SCHEDULED')
2025-07-06 02:10:49,778 - sqlalchemy.engine.Engine - INFO - [generated in 0.00112s] (UUID('09170749-d492-487c-b99d-e3fa7a35042b'), UUID('373788c0-0972-4754-9ac7-fe90eb2fa630'), None, UUID('2e418704-07da-448d-94a1-7bacf5f91b75'), datetime.datetime(2025, 7, 5, 0, 0), 'Fever', 'NORMAL', 'SCHEDULED')
2025-07-06 02:10:49,806 INFO sqlalchemy.engine.Engine COMMIT
2025-07-06 02:10:49,806 - sqlalchemy.engine.Engine - INFO - COMMIT
Appointment created with ID: 09170749-d492-487c-b99d-e3fa7a35042b
2025-07-06 02:10:49,813 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-06 02:10:49,813 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-06 02:10:49,816 INFO sqlalchemy.engine.Engine SELECT appointments.id, appointments.patient_id, appointments.doctor_id, appointments.created_by, appointments.appointment_date, appointments.reason, appointments.urgency, appointments.status, appointments.notes, appointments.created_at, appointments.updated_at
FROM appointments
WHERE appointments.id = %s
2025-07-06 02:10:49,816 - sqlalchemy.engine.Engine - INFO - SELECT appointments.id, appointments.patient_id, appointments.doctor_id, appointments.created_by, appointments.appointment_date, appointments.reason, appointments.urgency, appointments.status, appointments.notes, appointments.created_at, appointments.updated_at
FROM appointments
WHERE appointments.id = %s
2025-07-06 02:10:49,823 INFO sqlalchemy.engine.Engine [generated in 0.00676s] (UUID('09170749-d492-487c-b99d-e3fa7a35042b'),)
2025-07-06 02:10:49,823 - sqlalchemy.engine.Engine - INFO - [generated in 0.00676s] (UUID('09170749-d492-487c-b99d-e3fa7a35042b'),)
2025-07-06 02:10:49,828 INFO sqlalchemy.engine.Engine SELECT patients.id AS patients_id, patients.phone_number AS patients_phone_number, patients.password_hash AS patients_password_hash, patients.first_name AS patients_first_name, patients.last_name AS patients_last_name, patients.date_of_birth AS patients_date_of_birth, patients.gender AS patients_gender, patients.email AS patients_email, patients.address AS patients_address, patients.emergency_contact AS patients_emergency_contact, patients.emergency_contact_name AS patients_emergency_contact_name, patients.emergency_contact_relationship AS patients_emergency_contact_relationship, patients.is_active AS patients_is_active, patients.created_at AS patients_created_at, patients.updated_at AS patients_updated_at      
FROM patients
WHERE patients.id IN (%s)
2025-07-06 02:10:49,828 - sqlalchemy.engine.Engine - INFO - SELECT patients.id AS patients_id, patients.phone_number AS patients_phone_number, patients.password_hash AS patients_password_hash, patients.first_name AS patients_first_name, patients.last_name AS patients_last_name, patients.date_of_birth AS patients_date_of_birth, patients.gender AS patients_gender, patients.email AS patients_email, patients.address AS patients_address, patients.emergency_contact AS patients_emergency_contact, patients.emergency_contact_name AS patients_emergency_contact_name, patients.emergency_contact_relationship AS patients_emergency_contact_relationship, patients.is_active AS patients_is_active, patients.created_at AS patients_created_at, patients.updated_at AS patients_updated_at
FROM patients
WHERE patients.id IN (%s)
2025-07-06 02:10:49,831 INFO sqlalchemy.engine.Engine [generated in 0.00358s] (UUID('373788c0-0972-4754-9ac7-fe90eb2fa630'),)
2025-07-06 02:10:49,831 - sqlalchemy.engine.Engine - INFO - [generated in 0.00358s] (UUID('373788c0-0972-4754-9ac7-fe90eb2fa630'),)
2025-07-06 02:10:49,837 INFO sqlalchemy.engine.Engine SELECT appointments.id, appointments.patient_id, appointments.doctor_id, appointments.created_by, appointments.appointment_date, appointments.reason, appointments.urgency, appointments.status, appointments.notes, appointments.created_at, appointments.updated_at
FROM appointments
WHERE appointments.id = %s
2025-07-06 02:10:49,837 - sqlalchemy.engine.Engine - INFO - SELECT appointments.id, appointments.patient_id, appointments.doctor_id, appointments.created_by, appointments.appointment_date, appointments.reason, appointments.urgency, appointments.status, appointments.notes, appointments.created_at, appointments.updated_at
FROM appointments
WHERE appointments.id = %s
2025-07-06 02:10:49,841 INFO sqlalchemy.engine.Engine [generated in 0.00377s] (UUID('09170749-d492-487c-b99d-e3fa7a35042b'),)
2025-07-06 02:10:49,841 - sqlalchemy.engine.Engine - INFO - [generated in 0.00377s] (UUID('09170749-d492-487c-b99d-e3fa7a35042b'),)
Found appointment: 09170749-d492-487c-b99d-e3fa7a35042b
2025-07-06 02:10:49,846 INFO sqlalchemy.engine.Engine SELECT queue.id, queue.appointment_id, queue.patient_id, queue.doctor_id, queue.queue_number, queue.priority_score, queue.status, queue.estimated_wait_time, queue.called_at, queue.served_at, queue.created_at, queue.updated_at
FROM queue
WHERE appointment_id = %s AND queue.status IN (%s, %s)
2025-07-06 02:10:49,846 - sqlalchemy.engine.Engine - INFO - SELECT queue.id, queue.appointment_id, queue.patient_id, queue.doctor_id, queue.queue_number, queue.priority_score, queue.status, queue.estimated_wait_time, queue.called_at, queue.served_at, queue.created_at, queue.updated_at
FROM queue
WHERE appointment_id = %s AND queue.status IN (%s, %s)
2025-07-06 02:10:49,849 INFO sqlalchemy.engine.Engine [generated in 0.00168s] (UUID('09170749-d492-487c-b99d-e3fa7a35042b'), 'WAITING', 'SERVING')
2025-07-06 02:10:49,849 - sqlalchemy.engine.Engine - INFO - [generated in 0.00168s] (UUID('09170749-d492-487c-b99d-e3fa7a35042b'), 'WAITING', 'SERVING')   
2025-07-06 02:10:49,855 INFO sqlalchemy.engine.Engine SELECT max(queue_number) AS max_1
FROM queue
WHERE date(created_at) = %s
2025-07-06 02:10:49,855 - sqlalchemy.engine.Engine - INFO - SELECT max(queue_number) AS max_1
FROM queue
WHERE date(created_at) = %s
2025-07-06 02:10:49,857 INFO sqlalchemy.engine.Engine [generated in 0.00130s] (datetime.date(2025, 7, 6),)
2025-07-06 02:10:49,857 - sqlalchemy.engine.Engine - INFO - [generated in 0.00130s] (datetime.date(2025, 7, 6),)
Next queue number: 3
2025-07-06 02:10:49,868 INFO sqlalchemy.engine.Engine SELECT appointments.doctor_id, count(queue.id) AS queue_count 
FROM appointments JOIN queue ON queue.appointment_id = appointments.id
WHERE queue.status IN (%s, %s) AND CURRENT_DATE = date(queue.created_at) GROUP BY appointments.doctor_id ORDER BY queue_count ASC
2025-07-06 02:10:49,868 - sqlalchemy.engine.Engine - INFO - SELECT appointments.doctor_id, count(queue.id) AS queue_count
FROM appointments JOIN queue ON queue.appointment_id = appointments.id
WHERE queue.status IN (%s, %s) AND CURRENT_DATE = date(queue.created_at) GROUP BY appointments.doctor_id ORDER BY queue_count ASC
2025-07-06 02:10:49,872 INFO sqlalchemy.engine.Engine [cached since 0.1091s ago] ('WAITING', 'CALLED')
2025-07-06 02:10:49,872 - sqlalchemy.engine.Engine - INFO - [cached since 0.1091s ago] ('WAITING', 'CALLED')
No available doctors found
Priority score: 100
2025-07-06 02:10:49,878 INFO sqlalchemy.engine.Engine SELECT queue.id, queue.appointment_id, queue.patient_id, queue.doctor_id, queue.queue_number, queue.priority_score, queue.status, queue.estimated_wait_time, queue.called_at, queue.served_at, queue.created_at, queue.updated_at
FROM queue
WHERE queue.status = %s AND date(created_at) = %s ORDER BY priority_score DESC
2025-07-06 02:10:49,878 - sqlalchemy.engine.Engine - INFO - SELECT queue.id, queue.appointment_id, queue.patient_id, queue.doctor_id, queue.queue_number, queue.priority_score, queue.status, queue.estimated_wait_time, queue.called_at, queue.served_at, queue.created_at, queue.updated_at
FROM queue
WHERE queue.status = %s AND date(created_at) = %s ORDER BY priority_score DESC
2025-07-06 02:10:49,879 INFO sqlalchemy.engine.Engine [generated in 0.00148s] ('WAITING', datetime.date(2025, 7, 6))
2025-07-06 02:10:49,879 - sqlalchemy.engine.Engine - INFO - [generated in 0.00148s] ('WAITING', datetime.date(2025, 7, 6))
Estimated wait time: 30
Queue values: {'appointment_id': UUID('09170749-d492-487c-b99d-e3fa7a35042b'), 'patient_id': UUID('373788c0-0972-4754-9ac7-fe90eb2fa630'), 'queue_number': 
3, 'priority_score': 100, 'status': <QueueStatus.WAITING: 'waiting'>, 'estimated_wait_time': 30}
2025-07-06 02:10:49,886 INFO sqlalchemy.engine.Engine INSERT INTO queue (id, appointment_id, patient_id, queue_number, priority_score, status, estimated_wait_time) VALUES (%s, %s, %s, %s, %s, %s, %s) RETURNING queue.id, queue.appointment_id, queue.patient_id, queue.doctor_id, queue.queue_number, queue.priority_score, queue.status, queue.estimated_wait_time, queue.called_at, queue.served_at, queue.created_at, queue.updated_at
2025-07-06 02:10:49,886 - sqlalchemy.engine.Engine - INFO - INSERT INTO queue (id, appointment_id, patient_id, queue_number, priority_score, status, estimated_wait_time) VALUES (%s, %s, %s, %s, %s, %s, %s) RETURNING queue.id, queue.appointment_id, queue.patient_id, queue.doctor_id, queue.queue_number, queue.priority_score, queue.status, queue.estimated_wait_time, queue.called_at, queue.served_at, queue.created_at, queue.updated_at
2025-07-06 02:10:49,888 INFO sqlalchemy.engine.Engine [generated in 0.00154s] (UUID('70bc62df-2e47-4b4c-b924-2ec81474610d'), UUID('09170749-d492-487c-b99d-e3fa7a35042b'), UUID('373788c0-0972-4754-9ac7-fe90eb2fa630'), 3, 100, 'WAITING', 30)
2025-07-06 02:10:49,888 - sqlalchemy.engine.Engine - INFO - [generated in 0.00154s] (UUID('70bc62df-2e47-4b4c-b924-2ec81474610d'), UUID('09170749-d492-487c-b99d-e3fa7a35042b'), UUID('373788c0-0972-4754-9ac7-fe90eb2fa630'), 3, 100, 'WAITING', 30)
Error during queue insert: 'asyncpg.pgproto.pgproto.UUID' object has no attribute 'id'
2025-07-06 02:10:49,892 INFO sqlalchemy.engine.Engine ROLLBACK
2025-07-06 02:10:49,892 - sqlalchemy.engine.Engine - INFO - ROLLBACK
Trying simplified insert: {'appointment_id': UUID('09170749-d492-487c-b99d-e3fa7a35042b'), 'queue_number': 3, 'priority_score': 100, 'status': 'waiting', 'estimated_wait_time': 30}
2025-07-06 02:10:49,900 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-06 02:10:49,900 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-06 02:10:49,903 INFO sqlalchemy.engine.Engine INSERT INTO queue (id, appointment_id, queue_number, priority_score, status, estimated_wait_time) VALUES (%s, %s, %s, %s, %s, %s) RETURNING queue.id, queue.appointment_id, queue.patient_id, queue.doctor_id, queue.queue_number, queue.priority_score, queue.status, queue.estimated_wait_time, queue.called_at, queue.served_at, queue.created_at, queue.updated_at
2025-07-06 02:10:49,903 - sqlalchemy.engine.Engine - INFO - INSERT INTO queue (id, appointment_id, queue_number, priority_score, status, estimated_wait_time) VALUES (%s, %s, %s, %s, %s, %s) RETURNING queue.id, queue.appointment_id, queue.patient_id, queue.doctor_id, queue.queue_number, queue.priority_score, queue.status, queue.estimated_wait_time, queue.called_at, queue.served_at, queue.created_at, queue.updated_at
2025-07-06 02:10:49,903 INFO sqlalchemy.engine.Engine [generated in 0.00133s] (UUID('ecfd9089-c0e4-453c-aa19-8021a0f32cf3'), UUID('09170749-d492-487c-b99d-e3fa7a35042b'), 3, 100, 'WAITING', 30)
2025-07-06 02:10:49,903 - sqlalchemy.engine.Engine - INFO - [generated in 0.00133s] (UUID('ecfd9089-c0e4-453c-aa19-8021a0f32cf3'), UUID('09170749-d492-487c-b99d-e3fa7a35042b'), 3, 100, 'WAITING', 30)
2025-07-06 02:10:49,907 INFO sqlalchemy.engine.Engine COMMIT
2025-07-06 02:10:49,907 - sqlalchemy.engine.Engine - INFO - COMMIT
Error in add_to_queue: 'asyncpg.pgproto.pgproto.UUID' object has no attribute 'id'
Error adding to queue: 'asyncpg.pgproto.pgproto.UUID' object has no attribute 'id'
C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\sqlalchemy\sql\annotation.py:163: RuntimeWarning: coroutine 'AsyncAdapt_asyncpg_cursor._prepare_and_execute' was never awaited
  return object.__new__(cls)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py:61: RuntimeWarning: coroutine 'connect' was never awaited
  def __enter__(self):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2025-07-06 02:10:49,961 - main - ERROR - Unhandled exception: 13 validation errors:
  {'type': 'get_attribute_error', 'loc': ('response', 'appointment_date'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'reason'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'urgency'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; 
can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in 
an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'patient_id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'doctor_id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'created_by'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'status'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'notes'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted 
in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'created_at'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'updated_at'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'patient'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; 
can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'doctor'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_utils.py", line 76, in collapse_excgroups   
  |     yield
  |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 177, in __call__   
  |     async with anyio.create_task_group() as task_group:
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 772, in __aexit__   
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__ 
    |     with recv_stream, send_stream, collapse_excgroups():
    |                                    ^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\piuse\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    |     self.gen.throw(value)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups 
    |     raise exc
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__ 
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\main.py", line 58, in log_requests
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next    |     raise app_exc
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro     
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__  
    |     await self.simple_response(scope, receive, send, request_headers=headers)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    |     await self.app(scope, receive, send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    |     await route.handle(scope, receive, send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    |     response = await f(request)
    |                ^^^^^^^^^^^^^^^^
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    |     content = await serialize_response(
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response 
    |     raise ResponseValidationError(
    | fastapi.exceptions.ResponseValidationError: 13 validation errors:
    |   {'type': 'get_attribute_error', 'loc': ('response', 'appointment_date'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. 
Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'reason'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'urgency'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'patient_id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'doctor_id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been 
called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO 
attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'created_by'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'status'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'notes'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'created_at'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'updated_at'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'patient'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'doctor'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__     
    await self.app(scope, receive, _send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__       
    with recv_stream, send_stream, collapse_excgroups():
                                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piuse\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups       
    raise exc
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__       
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\main.py", line 58, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next      
    raise app_exc
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__        
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response    await self.app(scope, receive, send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__  
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app  
    raise exc
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app  
    await app(scope, receive, sender)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app  
    raise exc
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app  
    await app(scope, receive, sender)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response       
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 13 validation errors:
  {'type': 'get_attribute_error', 'loc': ('response', 'appointment_date'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'reason'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'urgency'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; 
can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in 
an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'patient_id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'doctor_id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'created_by'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'status'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'notes'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted 
in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'created_at'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'updated_at'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'patient'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; 
can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'doctor'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}

INFO:     127.0.0.1:50220 - "POST /api/v1/staff/appointments HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_utils.py", line 76, in collapse_excgroups   
  |     yield
  |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 177, in __call__   
  |     async with anyio.create_task_group() as task_group:
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 772, in __aexit__   
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 435, 
in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__     
    |     await super().__call__(scope, receive, send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__    
    |     await self.middleware_stack(scope, receive, send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    |     raise exc
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__ 
    |     with recv_stream, send_stream, collapse_excgroups():
    |                                    ^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\piuse\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    |     self.gen.throw(value)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups 
    |     raise exc
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__ 
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\main.py", line 58, in log_requests
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next    |     raise app_exc
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro     
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__  
    |     await self.simple_response(scope, receive, send, request_headers=headers)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    |     await self.app(scope, receive, send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    |     await route.handle(scope, receive, send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    |     response = await f(request)
    |                ^^^^^^^^^^^^^^^^
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    |     content = await serialize_response(
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response 
    |     raise ResponseValidationError(
    | fastapi.exceptions.ResponseValidationError: 13 validation errors:
    |   {'type': 'get_attribute_error', 'loc': ('response', 'appointment_date'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. 
Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'reason'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'urgency'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'patient_id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'doctor_id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been 
called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO 
attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'created_by'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'status'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'notes'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'created_at'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'updated_at'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'patient'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |   {'type': 'get_attribute_error', 'loc': ('response', 'doctor'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
    |
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__ 
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__     
    raise exc
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__     
    await self.app(scope, receive, _send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__       
    with recv_stream, send_stream, collapse_excgroups():
                                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piuse\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups       
    raise exc
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__       
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\main.py", line 58, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next      
    raise app_exc
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__        
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response    await self.app(scope, receive, send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__  
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app  
    raise exc
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app  
    await app(scope, receive, sender)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app  
    raise exc
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app  
    await app(scope, receive, sender)
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response       
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 13 validation errors:
  {'type': 'get_attribute_error', 'loc': ('response', 'appointment_date'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'reason'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'urgency'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; 
can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in 
an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'patient_id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'doctor_id'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'created_by'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'status'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'notes'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted 
in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'created_at'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'updated_at'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'patient'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; 
can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}
  {'type': 'get_attribute_error', 'loc': ('response', 'doctor'), 'msg': "Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)", 'input': <models.Appointment object at 0x000001F0EC875670>, 'ctx': {'error': "MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)"}}

2025-07-06 02:11:09,486 - main - INFO - Request: POST http://localhost:8000/api/v1/staff/patients/drafts
2025-07-06 02:11:10,033 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-06 02:11:10,033 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-07-06 02:11:10,039 INFO sqlalchemy.engine.Engine SELECT users.id, users.username, users.password_hash, users.email, users.first_name, users.last_name, users.role, users.is_active, users.created_at, users.updated_at
FROM users
WHERE users.id = %s
2025-07-06 02:11:10,039 - sqlalchemy.engine.Engine - INFO - SELECT users.id, users.username, users.password_hash, users.email, users.first_name, users.last_name, users.role, users.is_active, users.created_at, users.updated_at
FROM users
WHERE users.id = %s
2025-07-06 02:11:10,042 INFO sqlalchemy.engine.Engine [cached since 82.23s ago] (UUID('2e418704-07da-448d-94a1-7bacf5f91b75'),)
2025-07-06 02:11:10,042 - sqlalchemy.engine.Engine - INFO - [cached since 82.23s ago] (UUID('2e418704-07da-448d-94a1-7bacf5f91b75'),)
C:\Users\piuse\Desktop\Hospital_Queue_Management_System\backend\.venv\Lib\site-packages\sqlalchemy\orm\loading.py:794: RuntimeWarning: coroutine 'connect' 
was never awaited
  populators = {key: list(value) for key, value in cached_populators.items()}
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2025-07-06 02:11:10,151 INFO sqlalchemy.engine.Engine ROLLBACK
2025-07-06 02:11:10,151 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-07-06 02:11:10,151 - main - INFO - Response: 200 - Process time: 0.6652s